[package]
name = "dicewars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
rand = "0.8"
bevy_egui = "0.16"
bevy_obj = "0.8"
bevy_mod_picking = "0.9.0"